name: Python code testing

on:
  pull_request:
    branches: [ release ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        cd src
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev --deploy --system
    - name: Tests with pytest
      run: |
        cd src
        pytest tests
